# Generated by Django 2.2.5 on 2019-12-18 01:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tomo', '0005_auto_20191216_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 1, 49, 36, 701783, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 1, 49, 36, 699786, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='hosted_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 1, 49, 36, 699786, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_time',
            field=models.IntegerField(default=1),
        ),
    ]
