# Generated by Django 2.2.5 on 2020-01-13 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomo', '0006_auto_20191220_1540'),
        ('tomo', '0007_auto_20191218_1100'),
        ('tomo', '0006_auto_20191228_1315'),
    ]

    operations = [
    ]
