# Generated by Django 2.2.5 on 2020-01-13 00:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tomo', '0008_merge_20200113_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 0, 53, 44, 657668, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 0, 53, 44, 657668, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='hosted_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 0, 53, 44, 657668, tzinfo=utc)),
        ),
    ]
