# Generated by Django 2.2.5 on 2020-01-22 13:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tomo.models


class Migration(migrations.Migration):

    dependencies = [
        ('tomo', '0013_auto_20200121_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(default='/media/default.jpg', upload_to=tomo.models.getEventImageFolder),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 22, 13, 29, 10, 861855, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 22, 13, 29, 10, 859861, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='hosted_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 22, 13, 29, 10, 859861, tzinfo=utc)),
        ),
    ]
