# Generated by Django 2.2.5 on 2020-01-23 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomo', '0014_auto_20200122_2229'),
        ('tomo', '0014_auto_20200122_2237'),
    ]

    operations = [
    ]
