# Generated by Django 2.2.5 on 2020-01-23 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomo', '0016_auto_20200123_1518'),
        ('tomo', '0015_merge_20200123_1317'),
        ('tomo', '0015_merge_20200123_1305'),
    ]

    operations = [
    ]
