# Generated by Django 2.2.5 on 2020-01-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomo', '0016_auto_20200123_1507'),
        ('tomo', '0018_auto_20200123_1753'),
    ]

    operations = [
    ]
