# Generated by Django 2.2.5 on 2020-01-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomo', '0017_merge_20200123_1547'),
        ('tomo', '0022_auto_20200124_1514'),
    ]

    operations = [
    ]
